sudo: required
services: docker
language: minimal
env:
  - KUBERNETES_VERSION="v1.14.10" DOCKER_IMAGE_TAG="latest-1.14" MINIKUBE_VERSION="v1.0.1"
  - KUBERNETES_VERSION="v1.15.8" DOCKER_IMAGE_TAG="latest-1.15" MINIKUBE_VERSION="v1.2.0"
  - KUBERNETES_VERSION="v1.16.5" DOCKER_IMAGE_TAG="latest-1.16" MINIKUBE_VERSION="v1.2.0"
  - KUBERNETES_VERSION="v1.17.1" DOCKER_IMAGE_TAG="latest-1.17" MINIKUBE_VERSION="v1.2.0"
arch:
  - amd64
  - ppc64le
  - s390x
script:
  - ./build.sh bsycorp/kind:$DOCKER_IMAGE_TAG bsycorp/kind:$KUBERNETES_VERSION
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
    repo: bsycorp/kind
